Algoritmo  "Ler10numerosESomarEles"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : CARLOS ANDERSON
// Autor(a)    : RODRIGO LANDEIRO
// Data atual  : 18/04/2023
Var
   i, numero, soma: inteiro


Inicio
   para i de 1 ate 10 faca
      escreva ("digite um numero: ")
      leia(numero)
      soma <- numero + soma
   fimpara
   
   escreval()
   escreva("soma: ", soma)


Fimalgoritmo